<h1>ESTANDARIZACION</h1><br>

<img src="img/ITQ.png" alt="LOGO">

**Nombre:** *Gabriel Q. Pazmiño* <br>

**Fecha:** 05/05/2026 <br>


<h1>github</h1>
** https://github.com/Vanship77/cuadernoIA2026.git **

In [9]:
from sklearn import preprocessing
import numpy as np

In [10]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [11]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [12]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [13]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
# Comprobar si las matrices estandarizadas son iguales

# Compara ambas matrices elemento por elemento
# allclose devuelve True si son iguales (o muy similares por temas de decimales)
# Imprime en pantalla el resultado de la comparación
# True = son iguales
# False = hay diferencias
np.allclose(X_train_std, X_train_2_std)

True